#!/usr/bin/env bash
set -euo pipefail

# Usage: VOCALONIX_IP=... DOGRAH_IP=... bash generate-env.sh
# Defaults use the Hetzner outputs from the terraform run.

VOCALONIX_IP="${VOCALONIX_IP:-62.238.101.107}"
DOGRAH_IP="${DOGRAH_IP:-62.238.109.55}"
VOCALONIX_PRIVATE_IP="${VOCALONIX_PRIVATE_IP:-10.0.1.2}"
DOGRAH_PRIVATE_IP="${DOGRAH_PRIVATE_IP:-10.0.1.3}"

VOCALONIX_HOST="$(echo "$VOCALONIX_IP" | tr '.' '-').sslip.io"
DOGRAH_HOST="$(echo "$DOGRAH_IP" | tr '.' '-').sslip.io"

AUTH_SECRET=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 24)
REDIS_PASSWORD=$(openssl rand -hex 24)
MINIO_ROOT_PASSWORD=$(openssl rand -hex 24)
TURN_SECRET=$(openssl rand -hex 32)
OSS_JWT_SECRET=$(openssl rand -hex 32)
DOGRAH_SERVICE_PASSWORD=$(openssl rand -hex 24)
VOCALONIX_POSTGRES_PASSWORD=$(openssl rand -hex 24)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cat > "$SCRIPT_DIR/dograh/.env" <<EOF
ACME_EMAIL=nobody@sslip.io
TRAEFIK_NETWORK=traefik-proxy
TRAEFIK_CERTRESOLVER=letsencrypt
TRAEFIK_ENTRYPOINT=websecure

PUBLIC_HOST=$DOGRAH_HOST
PUBLIC_BASE_URL=https://$DOGRAH_HOST
TURN_HOST=$DOGRAH_IP
TURN_SECRET=$TURN_SECRET
ENABLE_COTURN=true
OSS_JWT_SECRET=$OSS_JWT_SECRET

POSTGRES_PASSWORD=$POSTGRES_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD

DOGRAH_VERSION=latest
EOF

cat > "$SCRIPT_DIR/vocalonix/.env" <<EOF
ACME_EMAIL=nobody@sslip.io
TRAEFIK_NETWORK=traefik-proxy
TRAEFIK_CERTRESOLVER=letsencrypt
TRAEFIK_ENTRYPOINT=websecure

VOCALONIX_POSTGRES_USER=vocalonix
VOCALONIX_POSTGRES_PASSWORD=$VOCALONIX_POSTGRES_PASSWORD
VOCALONIX_POSTGRES_DB=vocalonix

NODE_ENV=development
APP_ORIGIN=https://$VOCALONIX_HOST
API_PUBLIC_URL=https://$VOCALONIX_HOST
VOCALONIX_API_PUBLIC_URL=https://$VOCALONIX_HOST

AUTH_SECRET=$AUTH_SECRET
REQUIRE_EMAIL_VERIFICATION=false
RESEND_API_KEY=
EMAIL_FROM=Vocalonix <hello@vocalonix.ai>
MAGIC_LINK_TTL_SECONDS=300

DOGRAH_INTERNAL_URL=http://$DOGRAH_PRIVATE_IP:8000
DOGRAH_PUBLIC_API_URL=https://$DOGRAH_HOST
DOGRAH_WIDGET_URL=https://$VOCALONIX_HOST
DOGRAH_STORAGE_INTERNAL_URL=http://$DOGRAH_PRIVATE_IP:9000
DOGRAH_API_KEY=
DOGRAH_SERVICE_EMAIL=vocalonix@vocalonix.ai
DOGRAH_SERVICE_PASSWORD=$DOGRAH_SERVICE_PASSWORD
DOGRAH_SERVICE_NAME=Vocalonix
DOGRAH_WORKFLOW_NAME=Vocalonix Agent
DOGRAH_WIDGET_ALLOWED_DOMAINS=$VOCALONIX_HOST

PUBLIC_HOST=$VOCALONIX_HOST
EOF

echo "Generated:"
echo "  - $SCRIPT_DIR/dograh/.env"
echo "  - $SCRIPT_DIR/vocalonix/.env"
